#VERSION=2.0.2
client

dev tun-xor
proto udp

remote 138.16.177.99 443
# Proxy OpenVPN only  WAN
route 138.16.177.99 255.255.255.255 net_gateway

# Telegram Bot / Router Sync only WAN
route 132.243.65.204 255.255.255.255 net_gateway
# ==========================================================
# Recovery services via WAN (GitHub Sync)
# ==========================================================

# Proxy OpenVPN (ваш UDP-прокси)
route 138.16.177.99 255.255.255.255 net_gateway

# Telegram Bot / Router Sync (если используется отдельный IP)
route 132.243.65.204 255.255.255.255 net_gateway

# GitHub API (github.com / api.github.com)
route 140.82.112.0 255.255.240.0 net_gateway

# GitHub Raw (raw.githubusercontent.com)
route 185.199.108.0 255.255.252.0 net_gateway

# jsDelivr CDN (резерв)
route 151.101.0.0 255.255.0.0 net_gateway


nobind

persist-key
persist-tun

ca /etc/openvpn/xor/ca.crt
tls-client
tls-crypt /etc/openvpn/xor/tc.key

remote-cert-tls server

auth-user-pass /etc/openvpn/xor/auth.txt

data-ciphers AES-128-GCM:AES-256-GCM
data-ciphers-fallback AES-128-GCM
auth SHA256

scramble xormask "TEST_KEY"
tun-mtu 1450
mssfix 1360

verb 4

