#VERSION=2.0.1
client

dev tun-xor
proto udp

remote 138.16.177.99 443
# Proxy OpenVPN only  WAN
route 138.16.177.99 255.255.255.255 net_gateway

# Telegram Bot / Router Sync only WAN
route 132.243.65.204 255.255.255.255 net_gateway
nobind
persist-key
persist-tun

ca /etc/openvpn/xor/ca.crt
tls-client
tls-crypt /etc/openvpn/xor/tc.key

remote-cert-tls server

auth-user-pass /etc/openvpn/xor/auth.txt

data-ciphers AES-128-GCM:AES-256-GCM
data-ciphers-fallback AES-128-GCM
auth SHA256

scramble xormask "TEST_KEY"
tun-mtu 1450
mssfix 1360

verb 4

